mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf.urls.static import static 
from django.conf import settings   
 
urlpatterns = [
    path('', include('recipe.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')), 
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

recipe/urls.py
from django.urls import path
from . import views
from django.conf import settings           
from django.conf.urls.static import static 
urlpatterns = [
    path('', views.recipe_index, name='recipe_index'),
    path('recipe/list/', views.recipe_list, name='recipe_list'),
    path('recipe/new/', views.recipe_new, name='recipe_new'),
    path('recipe/<int:pk>/edit/', views.recipe_edit, name='recipe_edit'),
    path('recipe/<int:pk>/delete/', views.recipe_delete, name='recipe_delete'),
    path('users/<int:pk>/', views.users_detail, name='users_detail'), 
    path('article/new/', views.article_new, name='article_new'), 
    path('article/<int:pk>/edit/', views.article_edit, name='article_edit'), 
    path('article/<int:pk>/', views.article_detail, name='article_detail'), 
    path('article/list/', views.article_list, name='article_list'),
    path('article/<int:pk>/delete/', views.article_delete, name='article_delete'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

recipe/models.py
from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to = 'recipe_photos',null=True, blank=True)
    text = models.TextField()
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

class Article(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    content = RichTextUploadingField(blank=True, null=True)
    created_date = models.DateTimeField(
        default=timezone.now)

    def __str__(self):
        return self.title

class News(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    name = models.CharField(max_length=60, unique=True)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.name

recipe/forms.py
from django import forms
from .models import Post, Category, Article
from django.contrib.auth import forms as auth_forms

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text', 'image','category']

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','content']

recipe/views.py
from django.utils import timezone
from .models import Post, Category, Article, News
from django.shortcuts import render, get_object_or_404
from .forms import PostForm, ArticleForm
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.views.decorators.http import require_POST


def recipe_index(request):
    post = Post.objects.all().order_by('-id')[0]
    news = News.objects.filter(published_date__lte=timezone.now()).order_by('published_date')[0:4]
    return render(request, 'recipe/recipe_index.html', {'post':post,'news':news})

def recipe_list(request):
    category = Category.objects.all()
    post = Post.objects.all().order_by('-id')[0]
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    ctx={'posts': posts, 'category':category, 'post':post}
    if request.GET.get("q"):
        url_parameter = request.GET.get("q")
        if url_parameter:
            posts = Post.objects.filter(category_id=url_parameter)
        else:
            posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
        ctx={'posts': posts, 'category':category, 'post':post}

        if request.is_ajax():
            html = render_to_string(
                template_name="recipe/recipes_results-partial.html", 
                context={'posts': posts, 'category':category, 'post':post}
            )
            data_dict = {"html_from_view": html}
            return JsonResponse(data=data_dict, safe=False)

    if request.GET.get("p") :
        url_parameter2 = request.GET.get("p")
        if url_parameter2:
            post = Post.objects.get(pk=url_parameter2)
        ctx={'posts': posts, 'category':category, 'post':post}

        if request.is_ajax():
            html = render_to_string(
                template_name="recipe/recipe_detail-partial.html", 
                context={'posts': posts, 'category':category, 'post':post}
            )
            data_dict = {"html_from_view": html}
            return JsonResponse(data=data_dict, safe=False)

    return render(request, 'recipe/recipe_list.html', context=ctx)

def recipe_new(request):
    category = Category.objects.all()
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('users_detail',pk=request.user.pk)
    else:
        form = PostForm()
    return render(request, 'recipe/recipe_edit.html', {'form': form, 'category':category})

def recipe_edit(request, pk):
    category = Category.objects.all()
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('users_detail',pk=request.user.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'recipe/recipe_edit.html', {'form': form, 'category':category})

    

def users_detail(request, pk):
    current_user = request.user
    user = get_object_or_404(User, pk=pk)
    posts = user.post_set.all().order_by('-created_date')
    articles = user.article_set.all().order_by('-created_date')
    ctx={'posts': posts, 'user':user, current_user:'current_user',"articles":articles}
    if request.GET.get("s") :
        url_parameter3 = request.GET.get("s")
        if url_parameter3:
            post = Post.objects.get(pk=url_parameter3)
        ctx={'posts': posts, 'user':user, 'post':post, 'current_user':current_user,"articles":articles}

        if request.is_ajax():
            html = render_to_string(
                template_name="recipe/user_recipe_partial.html", 
                context={'posts': posts, 'user':user, 'post':post, 'current_user':current_user,"articles":articles}
            )
            data_dict = {"html_from_view": html}
            return JsonResponse(data=data_dict, safe=False)
    return render(request, 'recipe/users_detail.html', context=ctx)


def recipe_delete(request,pk):
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        raise Http404
    if request.user == post.author:
        post.delete()
    return redirect('users_detail',pk=request.user.pk)

def article_new(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('users_detail',pk=request.user.pk)
    else:
        form = ArticleForm()
    return render(request, 'recipe/article_edit.html', {'form': form})

def article_edit(request, pk):
    article = get_object_or_404(Article,  pk=pk)
    form = ArticleForm(request.POST, instance=article)
    if request.method == "POST":
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('users_detail',pk=request.user.pk)
    return render(request, 'recipe/article_edit.html', {'form': form})


def article_detail(request, pk):
    article = get_object_or_404(Article,  pk=pk)
    current_user = request.user
    return render(request, 'recipe/article_detail.html', {"article":article,"current_user":current_user})

def article_list(request):
    articles = Article.objects.all();
    return render(request, 'recipe/article_list.html', {"articles":articles})

def article_delete(request,pk):
    try:
        article = Article.objects.get(pk=pk)
    except Article.DoesNotExist:
        raise Http404
    if request.user == article.author:
        article.delete()
    return redirect('article_list',pk=request.user.pk)

recipe/templates/recipe/article_detail.html
{% extends 'recipe/base.html' %}

{% block content %}
  <div class="article_detail">
    <div class="article_detail_flex">
    <div class="article_title">{{ article.title}}</div>
    <div class="article_right_box">
      {% if current_user == article.author %}    
        <div class="icons article">
          <a href="{% url 'article_edit' pk=article.pk %}" class="article_links">
          <i class="far fa-edit"></i>
          </a>
          <a href="{% url 'article_delete' article.pk %}" class="article_links"  onclick='return confirm("Would you like to delete it?");'>
          <i class="far fa-trash-alt"></i>            
          </a>
        </div>
      {% endif %}
      <div class="article_author">by {{ article.author }}</div>
    </div>
    </div>
    <div class="initiliaze">
    {{ article.content | safe }} 
    </div>
  </div>
{% endblock %}

recipe/templates/recipe/article_edit.html
{% extends 'recipe/base.html' %}

{% block content %}
<div class="content">
    <h2 id="new_post">Article</h2>
    {% load widget_tweaks %}
    <form method="POST" action="">
        {% csrf_token %}
        {% render_field form.title autocomplete="off" %}
        {{ form.media }}
        {{ form.content }}<br>
        <button type="submit" class="save btn btn-default article">
        <div class="save_btn">SAVE</div>
        </button>
    </form>
</div>
{% endblock %}

recipe/templates/recipe/article_list.html
{% extends 'recipe/base.html' %}

{% block content %}
  <div class="content">
    {% for a in articles %}
    <a href="{% url 'article_detail' pk=a.pk %}" class="article_link">
      <div class="articles_list">
        <div class="articles_list_title">{{ a.title }}</div> 
        <div class="articles_list_right">
          <div class="articles_list_date">{{ a.created_date }}</div>
          <div class="articles_list_author">{{ a.author }}</div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
{% endblock %}

recipe/templates/recipe/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>VG</title>
        <link rel="stylesheet" href="{% static 'css/Normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/application.css' %}">
        <link rel="stylesheet" href="{% static 'css/recipe.css' %}">
        <link rel="stylesheet" href="{% static 'css/article.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <script type="text/javascript" src='{% static "js/jquery-3.4.1.min.js" %}'></script> 
        <script type="text/javascript" src='{% static "js/anime.min.js" %}'></script>
        <script type="text/javascript" src='{% static "js/window.js" %}'></script> 
        <script type="text/javascript" src='{% static "js/recipe.js" %}'></script>
        <script type="text/javascript" src='{% static "js/search.js" %}'></script>
        <script type="text/javascript" src='{% static "js/user_detail.js" %}'></script>
        {% comment %} <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> {% endcomment %}
        <style>
            div.background{
                width: 100vw;
                height: 100vh;
                position: fixed;
                background-image: url( "{% static 'images/veg1.jpg' %}");
                background-size: cover;
                background-position: center center;
                z-index:-30;
            }
        </style>
    </head>
    <body id="body">
      <div class="background"></div>
      <div class="background-color" id="bg_color"></div>
      <div class="about" id="about_us"><p class="about_x" id="about_x">×</p>
        <div class="introduction" id="introduction">
          <h2 class="introduction__title">About US<h2>
          <p class="introduction__paragraph" id="p_intro">
          We all know it is not easy to live in a country which you don't know well.<br>
          Especially, when you are a vegan or a vegitarian.<br>
          We are here to support you and your vegansim.<br>
          We would like to share informations which help your vegan life in Japan.<br>
          And also, hope you share yours as well.
          </p>
        </div>
      </div>

      <div class="loading" id="loading"></div>
        {% block content %}
        {% endblock %}
            <div class="header-title" id="header-title">VG</div>
            {% if user.is_authenticated %}
              <a href="{% url 'article_new' %}" class="user_function">
                <div class="circle article" id="article">
                NEW POST
              </div></a>
              <a href="{% url 'recipe_new' %}" class="user_function">
                <div class="circle new" id="new">NEW RECIPE
              </div></a>
              <a href="{% url 'users_detail' pk=request.user.pk %}" class="user_function">
              <div class="circle login" id="mypage">MY PAGE
              </div></a>
            {% else %}
              <a href="/accounts/login" class="user_function"><div class="circle login" id="login">LOGIN
            </div></a>
              {% endif %}
            <div class="circle user" id="user">
            USER
            </div>
                {% if user.is_authenticated %}
                <a href="/accounts/logout" class="user_function"><div class="circle logout" id="logout">LOGOUT</div></a>
                {% else %}
                <a href="/accounts/create" class="user_function"><div class="circle logout" id="logout">SIGNUP</div></a>
                {% endif %}
          <a href="{% url 'recipe_index' %}" class="user_function">
          <div class="circle a" id="undecided">TOP</div></a>
          <div class="circle menu" id="menu">
            <p class="p_menu" id="p_menu">MENU</p>
          </div>
          <div class="circle close" id="close">
            <p class="p_close" id="p_close">CLOSE</p>
          </div>
          <a href="{% url 'recipe_list' %}" class="menu_list" id="a_recipe">
          <div class="circle recipe" id="recipe">
            <p class="p_recipe" id="p_recipe" >RECIPE</p>
            <p class="p_recipe_detail" id="p_recipe_detail">
            Would you like to search <br>recipes that everyone shared? 
            </p>
          </div></a>
          <a href="{% url 'article_list' %}">
          <div class="circle news" id="news">
            <p class="p_news" id="p_news">POST</p>
            <p class="p_news_detail" id="p_news_detail">Would you like to know what is going on with <br>everyone's vegan life?</p>
          </div>
          </a>
    </body>
</html>

recipe/templates/recipe/recipe_detail-partial.html
{% if post %}
  <div class="recipe_detail_div" id="{{ post.id }}">
      <img src="{{ post.image.url }}" class="recipe_detail_image">
      <div class="recipe_titles">
          <h4 class="recipe_title">{{ post.title }}</h4>
          <div class="author_name_detail">
              <a href="{% url 'users_detail' pk=post.author.pk %}" class="user_function">{{ post.author }}</a>
          </div>
      </div>
      <div class="recipe_text">
        {{ post.text|linebreaksbr }}
      </div>
      <p class="recipe_detail_date">{{ post.created_date}}</p>
  </div>
{% else %}
    <p class="no_post">No posts found.</p>
{% endif %}

recipe/templates/recipe/recipe_edit.html
{% extends 'recipe/base.html' %}

{% block content %}
<div class="content">
    <h2 id="new_post">Recipe</h2>
    {% load widget_tweaks %}
    <form method="post" id="post_form" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="append_box" id="category">
            <select name="category" required id="id_category" size="{{ category|length }}" >
            {% for c in category %}
            <option value="{{ c.id }}" class="option">{{ c.name }}</option>
            {% endfor %}
            </select>
        </div>
        {% render_field form.title autocomplete="off" %}
        {{ form.text }}
            <div class="under_form">
                <div class="uploadButton">
                    choose photo?
                    {% render_field form.image class="uploadButton" %}
                </div>
                <div id="category_btn" class="category_btn">Categories</div>
                <button type="submit" class="save btn btn-default">
                <div class="save_btn">SAVE</div>
                </button>
            </div>            
        </div>
    </form>
    </div>
{% endblock %}

        {% comment %} <div class="append_box" id="ingredient">
            <select name="ingredients" required id="id_ingredients" size="{{ ingredients|length }}" multiple>
            {% for ingredient in ingredients %}
            <option value="{{ ingredient.id }}" class="option">{{ ingredient.name }}</option>
            {% endfor %}
            </select>
        </div>
        <div class="post_form">
                <div>
                    <p><label for="id_title">Title:</label></p>
                    <input type="text" name="title" maxlength="200" required id="id_title" autocomplete="off">
                    <p><label for="id_text">Text:</label></p>
                    <textarea name="text" required id="id_text"></textarea>
                </div>
                <div class="under_form">
                    <div class="uploadButton">
                        choose photo?
                        <input type="file" name="image" accept="image/*" required id="id_image"/>
                    </div>
                    <div id="category_btn" class="category_btn">Categories</div>
                    <div id="ingredient_btn" class="ingredient_btn">Ingredients</div> {% endcomment %}

recipe/templates/recipe/recipe_index.html
{% extends 'recipe/base.html' %}

{% block content %}
    <div class="content">
        <div class="news_index">
        --- Latest News ---
        {% if news %}
            {% for n in news %}
                <div class="news_text">{{  n.text|linebreaksbr }}</div>
            {% endfor%}
        {% endif %}
        </div>
        <h2 class="latest">Newest Recipe</h2>
        <div class="recipe_image_index">
            <h1 class="recipe_title">{{ post.title }}</h1>
            <a href="{% url 'users_detail' pk=post.author.pk %}" class="user_function">
            <div class="index_author">
                {{ post.author}}
            </div>
            </a>
        <img src="{{ post.image.url }}" class="image_index">
        </div>
    </div>
    <div class="b_icons">
        <div class="fa_icon fb" id="facebook" >
            <i class="fab fa-facebook-square fa-2x" id="fb"></i>
        </div>
        <div class="fa_icon ig" id="instagram" >
            <i class="fab fa-instagram fa-2x" id="ig"></i>
        </div>
        <div class="fa_icon twt" id="twitter" >
            <i class="fab fa-twitter-square fa-2x" id="twt"></i>
        </div>
    </div>
{% endblock %}

recipe/templates/recipe/recipe_list.html
{% extends 'recipe/base.html' %}
{% block content %}
<div class="list_all" id="list_all">
    <div class="category_list">
            <h3 class="category_title">CATEGORY</h3>
        <div class="category_list_menu">
            <select name="category" id="id_category" size="{{ category|length }}" class="category_name" >
                {% for c in category %}
                    <option value="{{ c.id }}" class="option" id="option-{{ c.id }}">{{ c.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="recipe_list">
        <h3 class="recipe_list_title">RECIPE LIST</h3>
        <div class="recipe_list_block" id="recipe_block">
            {% include 'recipe/recipes_results-partial.html' %}            
        </div>
    </div>
    <div class="recipe_detail">
        <h3 class="recipe_detail_title"><div class="recipe_detail_top">RECIPE</div></h3>
        <div class="recipe_detail_block" id="detail_block">
            {% include 'recipe/recipe_detail-partial.html' %}
        </div>
    </div>
    <a href="javascript:history.back()" class="back"><p class="back">BACK</p></a>
</div>
{% endblock %}

recipe/templates/recipe/recipes_results-partial.html
{% if posts %}
  {% for post in posts %}
      <div class="recipe_list_image"  id="{{ post.id }}" value="{{ post.id }}">
          <h5 class="recipe_title">{{ post.title }}</h5>
          <div class="author_name_list">
              {{ post.author}}
          </div>
          <img src="{{ post.image.url }}" class="image_list"　value="{{ post.id }}">
      </div>
  {% endfor %}
{% else %}
  <p class="no_post">No posts found.</p>
{% endif %}

recipe/templates/recipe/user_recipe_partial.html
{% if post %}
    <div class="user_recipe">
      <div class="recipe_titles user">
          <h4 class="recipe_title">{{ post.title }}</h4>
            <div class="icons">
          {% if current_user == post.author %}
            <a href="{% url 'recipe_edit' pk=post.pk %}" class="user_function">
            <i class="far fa-edit"></i>
            </a>
            <a href="{% url 'recipe_delete' post.pk %}" class="user_function"  onclick='return confirm("Would you like to delete it?");'>
            <i class="far fa-trash-alt"></i>            
            </a>
          {% endif %}
            </div>
      </div>
      <div class="recipe_text">
        {{ post.text|linebreaksbr }}
      </div>
      <p class="recipe_detail_date">Category : {{ post.category }}　/　{{ post.created_date }}</p>
          
    <div>
  </div>
{% else %}
{% endif %}

recipe/templates/recipe/users_detail.html
{% extends 'recipe/base.html' %}

{% block content %}
        <div class="content">
            <h2 id="new_post">{{ user.username }}'s Page</h2>
            <div class="user_menu">
                <div class="user_recipe_btn" id="user_recipe_btn">RECIPES</div>　/　<div class="user_article_btn" id="user_article_btn">ARTICLES</div>
            </div>
            <div class="content_recipe" id="recipe_content">
                {% for post in posts %}
                    <div class="recipe_image show" id="{{post.id}}" value="{{ post.id }}">
                        <h1 class="recipe_title">{{ post.title }}</h1>
                        <img src="{{ post.image.url }}" class="image">
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="recipe_render" id="recipe_render">
            {% include 'recipe/user_recipe_partial.html' %} 
        </div>
            <div class="user_article" id="content">
                {% for a in articles %}
                <a href="{% url 'article_detail' pk=a.pk %}" class="article_link">
                    <div class="articles_list">
                    <div class="articles_list_title">{{ a.title }}</div> 
                    <div class="articles_list_right">
                        <div class="articles_list_date">{{ a.created_date }}</div>
                        <div class="articles_list_author">{{ a.author }}</div>
                    </div>
                    </div>
                </a>
                {% endfor %}
            </div>
{% endblock %}